'use strict';
const ROUTES={visionairy:{today:'/',outreach:'/email',activity:'/pipeline',companies:'/list'},stockerai:{today:'/products/stockerai?filter=today',outreach:'/products/stockerai',activity:'/products/stockerai?filter=activity',companies:'/products/stockerai?filter=all'}};
function navigation({productId='visionairy',active='today'}={}){
 const product=productId==='stockerai'?'stockerai':'visionairy',routes=ROUTES[product];
 const link=(key,label)=>`<a href="${routes[key]}"${active===key?' aria-current="page" class="current"':''}>${label}</a>`;
 return `<header class="crm-shell"><div class="product-switch" aria-label="Choose outreach product"><span>Working in</span><a href="/"${product==='visionairy'?' class="selected"':''}>VisionAIry</a><a href="/products/stockerai"${product==='stockerai'?' class="selected"':''}>StockerAI</a></div><nav class="primary-work" aria-label="Primary work areas">${link('today','Today')}${link('outreach','Outreach')}${link('activity','Activity')}${link('companies','Companies')}</nav><details class="more-work"><summary>More</summary><div>${product==='visionairy'?'<a href="/progress">Reports</a><a href="/people">People</a><a href="/linkedin">LinkedIn</a><a href="/needemail">Missing email</a><a href="/money">Money</a><a href="/add">Add a company</a>':'<a href="/products/stockerai?filter=needs_setup">Needs preparation</a><a href="/products/stockerai?filter=stopped">Stopped campaigns</a>'}</div></details></header>`;
}
const styles=`.crm-shell{display:grid;grid-template-columns:auto 1fr auto;align-items:center;gap:18px;padding:12px 0;margin:0 0 16px;border-bottom:2px solid var(--line,#dfe4e8)}.product-switch{display:flex;align-items:center;gap:6px;white-space:nowrap}.product-switch span{font-size:12px;color:var(--muted,#68727c);margin-right:3px}.product-switch a,.primary-work a,.more-work a{color:var(--ink,#17212b);text-decoration:none;border-radius:8px;padding:7px 10px;font-weight:650}.product-switch a{border:1px solid var(--line,#dfe4e8);font-size:13px}.product-switch a.selected{background:var(--moss,#386641);border-color:var(--moss,#386641);color:white}.primary-work{display:flex;justify-content:center;gap:5px;margin:0}.primary-work a.current,.primary-work a[aria-current="page"]{background:#e8f2df;color:#264c2e}.more-work{position:relative}.more-work summary{cursor:pointer;list-style:none;border:1px solid var(--line,#dfe4e8);border-radius:8px;padding:7px 11px;font-weight:650}.more-work[open] div{position:absolute;right:0;top:42px;z-index:80;background:white;border:1px solid var(--line,#dfe4e8);border-radius:10px;box-shadow:0 10px 30px #17212b22;padding:7px;min-width:180px;display:grid}.more-work a{font-size:14px}@media(max-width:720px){.crm-shell{grid-template-columns:1fr auto}.product-switch{grid-column:1/3}.primary-work{justify-content:flex-start;overflow-x:auto}.primary-work a{padding:7px 8px}}`;
module.exports={navigation,styles,ROUTES};
